# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define _binary_filedigest_algorithm 1
%define _binary_payload w9.gzdio

BuildArch:     noarch
Name:          fdt
Version:       0.20
Release:       1
License:       Caltech
Group:         System Environment/Libraries
Summary:       Fast Data Transfer tool
URL:           http://monalisa.cern.ch/FDT

Provides:      fdt = 0.20
Requires:      jdk >= 1.6
Requires:      jpackage-utils
#suggest
#enhance
%description
Fast Data Transfer tool
%files
%attr(0644, root, root) "/usr/share/java/fdt-0.20.0.jar"
%attr(0777, root, root) "/usr/share/java/fdt.jar"

%changelog
* Mon Oct 20 2014 Vlad Lapadatescu <vlad@caltech.edu> 0.20
- Updated to latest FDT version

* Wed Jan 22 2014 Vlad Lapadatescu <vlad@caltech.edu> 0.19.2
- Updated to latest FDT version

* Thu Nov 14 2013 Vlad Lapadatescu <vlad@caltech.edu> 0.19.0
- Update to latest version (sync not forced on file close).
Everything should work fine though...

* Tue Oct 15 2013 Vlad Lapadatescu <vlad@caltech.edu> 0.18.6
- Update to latest latest :) version

* Tue Jun 19 2012 Michael Thomas <thomas@hep.caltech.edu> 0.10.12-1
- Update to latest version

* Mon Oct 04 2010 Michael Thomas <thomas@hep.caltech.edu> 0.9.18-1
- Update to latest prerelease with close() fix

* Thu Sep 09 2010 Michael Thomas <thomas@hep.caltech.edu> 0.9.17-3
- Bump release to test koji build

* Wed Sep 08 2010 Michael Thomas <thomas@hep.caltech.edu> 0.9.17-2
- New upstream prerelease that fixes a hang when the grid-mapfile is missing

* Tue Aug 31 2010 Michael Thomas <thomas@hep.caltech.edu> 0.9.17-1
- New upstream release that does not try to create a apmon.log file

* Mon Aug 23 2010 Michael Thomas <thomas@hep.caltech.edu> 0.9.16-1
- Initial version after separating fdt and fdt-hdfs