# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0

%define _binary_filedigest_algorithm 1
%define _binary_payload w9.gzdio

BuildArch:     noarch
Name:          fdt
Version:       0.25
Release:       1
License:       ACL 2.0
Group:         System Environment/Libraries
Summary:       Fast Data Transfer tool
URL:           http://monalisa.cern.ch/FDT

Provides:      fdt = %{version}
Requires:      jdk >= 1.6
Requires:      jpackage-utils
#suggest
#enhance
%description
Fast Data Transfer tool
%files
%attr(0644, root, root) "/usr/share/java/fdt-0.25.0.jar"
%attr(0777, root, root) "/usr/share/java/fdt.jar"

